# THERAC-25 Simulation - Optimized for Quality Pipeline
# Only Web UI container needed for all testing scenarios

services:
  # Web UI Container - Spanish Interface with Full Bug Simulation
  therac_web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: therac25_web
    environment:
      - VERSION=buggy
      - DEBUG_MODE=true
      - FLASK_ENV=development
    volumes:
      - ./logs:/app/logs:rw
      - ./reports:/app/reports:rw
    networks:
      - therac_network
    ports:
      - "8080:8080"
    command: ["python", "src/web_interface/app.py"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  therac_network:
    driver: bridge
    name: therac25_network

volumes:
  therac_logs:
    driver: local
  therac_reports:
    driver: local